language: java
dist: xenial
notifications:
  email:
    recipients:
    - middleware@hexonet.net
    on_success: never
    on_failure: always
install: true
addons:
  apt:
    update: true
jdk:
  - oraclejdk11
  - openjdk11
  - openjdk-ea
matrix:
  allow_failures:
    - jdk: openjdk-ea
# Trigger a push build on master and dependabot branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^dependabot.*$/
script:
  - mvn site
  - mvn package
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - openssl aes-256-cbc -K $encrypted_c9f9aedf26b7_key -iv $encrypted_c9f9aedf26b7_iv -in codesigning.asc.enc -out codesigning.asc -d
        - gpg --import --batch codesigning.asc
        - npm prune
        - travis_retry npm i
        - npx semantic-release