name: Release
on:
  # will run for every branch, except tags. See RSRMID-206.
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - "master"

jobs:
  release:
    name: Release Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Download Maven build artifact
        uses: actions/download-artifact@v3
        with:
          name: target.zip
      - run: |
          unzip -o target.zip
          rm target.zip
      - uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "adopt"
      - name: Setup NodeJS LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          MAVEN_OPTS: ${{ secrets.MAVEN_OPTS }}
          OSSRH_JIRA_USERNAME: ${{ secrets.OSSRH_JIRA_USERNAME }}
          OSSRH_JIRA_PASSWORD: ${{ secrets.OSSRH_JIRA_PASSWORD }}
          ENCRYPTED_C9F9AEDF26B7_KEY: ${{ secrets.ENCRYPTED_C9F9AEDF26B7_KEY }}
          ENCRYPTED_C9F9AEDF26B7_IV: ${{ secrets.ENCRYPTED_C9F9AEDF26B7_IV }}
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          openssl aes-256-cbc -K $ENCRYPTED_C9F9AEDF26B7_KEY -iv $ENCRYPTED_C9F9AEDF26B7_IV -in codesigning.asc.enc -out codesigning.asc -d
          gpg --import --batch codesigning.asc
          npx semantic-release
