name: Dependabot auto-merge & tests
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: write

jobs:
  tests:
    uses: centralnicgroup-opensource/rtldev-middleware-shareable-workflows/.github/workflows/java-sdk-test.yml@main
    secrets: inherit