name: Test

on:
  push:
    branches:
      - dependabot/**

  pull_request:
    types:
      - opened
      - synchronize

  workflow_call:

jobs:
  # separate job to set as required in branch protection,
  # as the build names above change each time Node versions change
  test:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Super Linter Code Base
        uses: github/super-linter@v4
        env:
          FILTER_REGEX_INCLUDE: "((/src/main/.*.java)|updateVersion.sh)"
          DEFAULT_BRANCH: master
          VALIDATE_GOOGLE_JAVA_FORMAT: true
          VALIDATE_BASH: true
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test_matrix:
    strategy:
      matrix:
        java-version:
          - 16
          - 17
          - 18

    runs-on: ubuntu-latest
    needs: test
    name: Test @ Java JDK ${{ matrix.java-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Java JDK @^${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
      - name: Validate & Coverage Report
        run: |
          mvn -B clean site package
          zip -r /home/runner/target.zip ./target
      - uses: actions/upload-artifact@v3
        id: upload
        with:
          name: coverage
          path: ~/target.zip
          retention-days: 1
